### ISSUE TITLE
启动前端项目时报错

### ISSUE THREAD

**Issue by coolliuan** [Z-J-wang/molstar-viewer-vue#5]
Uncaught SyntaxError: The requested module '/node_modules/molstar/build/viewer/molstar.js?v=8696983c' does not provide an export named 'ExtensionMap' (at MolStarViewer.vue? [sm]:3:47)
![Uploading 微信图片_20240529153046.png…]()

**Comment by Z-J-wang** [comment]
你的项目安装的molstar版本是4.0.1吗？
这个报错是因为 '/node_modules/molstar/build/viewer/molstar.js?v=8696983c' 文件不导出ExtensionMap变量导致的。大概率是molstat版本不一致导致的。

**Comment by chenyuyou1** [comment]
你包设置的molstar ^ 4.0.1版本，结果不兼容molstar 4.6.0版本

**Comment by chenyuyou1** [comment]
而且4.0.1这个版本是这个报错： '/node_modules/molstar-viewer-vue/node_modules/molstar/build/viewer/molstar.js?v=7e0e4f9c' does not provide an export named 'ExtensionMap'

**Comment by chenyuyou1** [comment]
用vite初始项目跑的

**Comment by Z-J-wang** [comment]
我这边验证了，和`molstar`版本没有关系。只需要在项目中引入molstar环境即可。如下：

```js
import 'molstar/build/viewer/molstar' // 引入molstar环境，必须
import MolStarViewer from 'molstar-viewer-vue'
```

**Comment by cyy999yyc** [comment]
按你这样设置后跑起来了，但是代码层面会报错。如下：
找不到模块“molstar-viewer-vue”或其相应的类型声明。ts-plugin(2307)

**Comment by cyy999yyc** [comment]
我想问一下，怎么修改你这个组件的宽高？

**Comment by Z-J-wang** [comment]
> 按你这样设置后跑起来了，但是代码层面会报错。如下： 找不到模块“molstar-viewer-vue”或其相应的类型声明。ts-plugin(2307)

这是`molstar-viewer-vue`不是ts组件。而你在ts项目中使用导致的。只需要在全局的`env.d.ts`声明文件做声明即可。如下：

```ts
/// <reference types="vite/client" />
declare module '*.vue' {
  import type { DefineComponent } from 'vue'
  const vueComponent: DefineComponent<{}, {}, any>
  export default vueComponent
}

declare module 'molstar-viewer-vue' // 声明 molstar-viewer-vue

```

**Comment by Z-J-wang** [comment]
> 我想问一下，怎么修改你这个组件的宽高？

molstar 本身并没有提供宽高的设置。所以组件也没法设置宽高。
